FROM ubuntu:xenial

# metadata
LABEL base.image="ubuntu:xenial"
LABEL software="jq"
LABEL software.version="1.6"
LABEL dexcription="JSON processor"
LABEL website="https://jqlang.github.io/jq/"
LABEL maintainer="Neranjan Perera"
LABEL maintainer.email="neranjan.perera007@gmail.com"

RUN apt-get update
